const routes = {
  '/': 'Home',
  '/dashboard': 'Dashboard',
  '/components': 'Components',
  '/charts': 'Charts',
  '/gestions': 'Gestions',
  '/gestions/utilisateurs':'Utilisateurs',
  '/gestions/scooters':'Scooters',
  '/gestions/droitsdeconduite':'Droits de Conduite',
  '/gestions/conducteurs':'Conducteurs',
  '/gestions/contrats':'Contrats',
  '/gestions/batteries':'Batteries',
  '/gestions/chargeurs':'Chargeurs',
  '/gestions/stocks':'Stocks',
  '/gestions/boitiers':'Boitiers',
  '/gestions/flottes':'Flottes',
  '/gestions/clients':'Clients',
  '/gestions/facturations':'Facturations',
  '/gestions/interventions':'Interventions',
  '/gestions/notifications':'Notifications',
  '/gestions/alertes':'Alertes',
  '/components/buttons': 'Buttons',
  '/components/social-buttons': 'Social Buttons',
  '/components/cards': 'Cards',
  '/components/forms': 'Forms',
  '/components/modals': 'Modals',
  '/components/switches': 'Switches',
  '/components/tables': 'Tables',
  '/components/tabs': 'Tabs',
  '/icons': 'Icons',
  '/icons/font-awesome': 'Font Awesome',
  '/icons/simple-line-icons': 'Simple Line Icons',
  '/widgets': 'Widgets'
};
export default routes;
